import { Request, Proposal, Engagement } from '../types';

export const mockRequests: Request[] = [
  {
    id: 'req-001',
    title: 'Innovate Corp - FY2023 Financial Audit',
    description: 'Annual financial audit for Innovate Corp covering the fiscal year 2023. Company operates in the technology sector with multiple subsidiaries.',
    clientName: 'Innovate Corp',
    clientEmail: 'finance@innovatecorp.com',
    framework: 'IFRS',
    businessSize: 'Large',
    financialYearEnd: '2023-12-31',
    deliveryDeadline: '2024-04-30',
    budget: '120000',
    urgency: 'Normal',
    isTaxReturnNeeded: 'Yes',
    notes: 'Company has international operations. Need auditor with IFRS expertise.',
    status: 'Open',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z'
  },
  {
    id: 'req-002',
    title: 'Global Tech Inc - Q1 2024 Tax Provision',
    description: 'Quarterly tax provision calculation and review for Q1 2024. Company has complex tax structure with multiple jurisdictions.',
    clientName: 'Global Tech Inc',
    clientEmail: 'tax@globaltech.com',
    framework: 'IFRS',
    businessSize: 'Medium',
    financialYearEnd: '2024-03-31',
    deliveryDeadline: '2024-04-25',
    budget: '45000',
    urgency: 'Urgent',
    isTaxReturnNeeded: 'No',
    notes: 'Urgent deadline due to board meeting. Need experienced tax professional.',
    status: 'In Progress',
    createdAt: '2024-04-01T14:30:00Z',
    updatedAt: '2024-04-05T09:15:00Z'
  },
  {
    id: 'req-003',
    title: 'Sunrise Retail - Internal Controls Review',
    description: 'Comprehensive review of internal controls for Sunrise Retail chain. Focus on inventory and cash management systems.',
    clientName: 'Sunrise Retail',
    clientEmail: 'audit@sunriseretail.com',
    framework: 'GAPSME',
    businessSize: 'Medium',
    financialYearEnd: '2024-02-29',
    deliveryDeadline: '2024-05-30',
    budget: '75000',
    urgency: 'Normal',
    isTaxReturnNeeded: 'Yes',
    notes: 'Retail chain with 15 locations. Need auditor familiar with retail operations.',
    status: 'Open',
    createdAt: '2024-02-01T11:20:00Z',
    updatedAt: '2024-02-01T11:20:00Z'
  },
  {
    id: 'req-004',
    title: 'Legacy Bank - Due Diligence Project',
    description: 'Financial due diligence for potential acquisition target. Need detailed analysis of financial statements and projections.',
    clientName: 'Legacy Bank',
    clientEmail: 'm&a@legacybank.com',
    framework: 'IFRS',
    businessSize: 'Large',
    financialYearEnd: '2024-01-31',
    deliveryDeadline: '2024-04-20',
    budget: '95000',
    urgency: 'Urgent',
    isTaxReturnNeeded: 'No',
    notes: 'Confidential project. NDA required. Need senior auditor with M&A experience.',
    status: 'Open',
    createdAt: '2024-03-10T16:45:00Z',
    updatedAt: '2024-03-10T16:45:00Z'
  },
  {
    id: 'req-005',
    title: 'SmallBiz Co - 2023 Annual Tax Filing',
    description: 'Annual corporate tax return preparation and filing for SmallBiz Co. Simple structure with minimal complexity.',
    clientName: 'SmallBiz Co',
    clientEmail: 'admin@smallbizco.com',
    framework: 'GAPSME',
    businessSize: 'Small',
    financialYearEnd: '2023-12-31',
    deliveryDeadline: '2024-04-15',
    budget: '8500',
    urgency: 'Normal',
    isTaxReturnNeeded: 'Yes',
    notes: 'Small business with straightforward tax situation. Looking for cost-effective solution.',
    status: 'Completed',
    createdAt: '2024-02-20T08:30:00Z',
    updatedAt: '2024-04-15T17:00:00Z'
  }
];

export const mockProposals: Proposal[] = [
  {
    id: 'prop-001',
    requestId: 'req-001',
    auditorName: 'Sarah Johnson',
    auditorEmail: 'sarah.johnson@auditfirm.com',
    auditorId: 'aud-001',
    title: 'Innovate Corp FY2023 Audit Proposal',
    description: 'Comprehensive audit proposal for Innovate Corp covering all aspects of the financial statements and internal controls.',
    proposedBudget: 115000,
    estimatedDuration: '12 weeks',
    startDate: '2024-02-01',
    endDate: '2024-04-25',
    status: 'Accepted',
    terms: 'Payment 50% upfront, 50% upon completion. Includes tax return preparation.',
    deliverables: [
      'Audit report with unqualified opinion',
      'Management letter with recommendations',
      'Tax return preparation and filing',
      'Quarterly review meetings'
    ],
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-25T14:30:00Z'
  },
  {
    id: 'prop-002',
    requestId: 'req-001',
    auditorName: 'Michael Chen',
    auditorEmail: 'michael.chen@auditfirm.com',
    auditorId: 'aud-002',
    title: 'Innovate Corp Audit Engagement',
    description: 'Professional audit services with focus on technology sector expertise and international operations.',
    proposedBudget: 125000,
    estimatedDuration: '14 weeks',
    startDate: '2024-02-15',
    endDate: '2024-05-15',
    status: 'Rejected',
    terms: 'Payment 30% upfront, 40% at midpoint, 30% upon completion.',
    deliverables: [
      'Audit report',
      'Internal control assessment',
      'Tax planning consultation',
      'Quarterly reviews'
    ],
    createdAt: '2024-01-22T11:15:00Z',
    updatedAt: '2024-01-28T10:45:00Z'
  },
  {
    id: 'prop-003',
    requestId: 'req-002',
    auditorName: 'Emily Rodriguez',
    auditorEmail: 'emily.rodriguez@auditfirm.com',
    auditorId: 'aud-003',
    title: 'Global Tech Q1 Tax Provision',
    description: 'Specialized tax provision services with expertise in multi-jurisdictional tax compliance.',
    proposedBudget: 42000,
    estimatedDuration: '3 weeks',
    startDate: '2024-04-05',
    endDate: '2024-04-25',
    status: 'Accepted',
    terms: 'Full payment upon completion. Includes tax planning consultation.',
    deliverables: [
      'Q1 tax provision calculation',
      'Tax planning recommendations',
      'Compliance review',
      'Board presentation support'
    ],
    createdAt: '2024-04-02T13:20:00Z',
    updatedAt: '2024-04-03T16:00:00Z'
  },
  {
    id: 'prop-004',
    requestId: 'req-003',
    auditorName: 'David Thompson',
    auditorEmail: 'david.thompson@auditfirm.com',
    auditorId: 'aud-004',
    title: 'Sunrise Retail Controls Review',
    description: 'Comprehensive internal controls review with focus on retail operations and inventory management.',
    proposedBudget: 72000,
    estimatedDuration: '8 weeks',
    startDate: '2024-03-01',
    endDate: '2024-04-26',
    status: 'Pending',
    terms: 'Payment 40% upfront, 30% at midpoint, 30% upon completion.',
    deliverables: [
      'Internal controls assessment report',
      'Risk assessment',
      'Process improvement recommendations',
      'Staff training materials'
    ],
    createdAt: '2024-02-05T15:30:00Z',
    updatedAt: '2024-02-05T15:30:00Z'
  },
  {
    id: 'prop-005',
    requestId: 'req-004',
    auditorName: 'Lisa Wang',
    auditorEmail: 'lisa.wang@auditfirm.com',
    auditorId: 'aud-005',
    title: 'Legacy Bank Due Diligence',
    description: 'Financial due diligence services with extensive M&A experience in the financial services sector.',
    proposedBudget: 98000,
    estimatedDuration: '6 weeks',
    startDate: '2024-03-15',
    endDate: '2024-04-26',
    status: 'Pending',
    terms: 'Payment 50% upfront, 50% upon completion. Includes NDA compliance.',
    deliverables: [
      'Financial due diligence report',
      'Quality of earnings analysis',
      'Working capital assessment',
      'Management presentation'
    ],
    createdAt: '2024-03-12T10:00:00Z',
    updatedAt: '2024-03-12T10:00:00Z'
  }
];

export const mockEngagements: Engagement[] = [
  {
    id: 'eng-001',
    proposalId: 'prop-001',
    requestId: 'req-001',
    clientName: 'Innovate Corp',
    clientEmail: 'finance@innovatecorp.com',
    auditorName: 'Sarah Johnson',
    auditorEmail: 'sarah.johnson@auditfirm.com',
    projectName: 'Innovate Corp - FY2023 Financial Audit',
    startDate: '2024-02-01',
    endDate: '2024-04-25',
    budget: 115000,
    status: 'Completed',
    framework: 'IFRS',
    businessSize: 'Large',
    isTaxReturnNeeded: true,
    createdAt: '2024-01-25T14:30:00Z',
    updatedAt: '2024-04-25T17:00:00Z'
  },
  {
    id: 'eng-002',
    proposalId: 'prop-003',
    requestId: 'req-002',
    clientName: 'Global Tech Inc',
    clientEmail: 'tax@globaltech.com',
    auditorName: 'Emily Rodriguez',
    auditorEmail: 'emily.rodriguez@auditfirm.com',
    projectName: 'Global Tech Inc - Q1 2024 Tax Provision',
    startDate: '2024-04-05',
    endDate: '2024-04-25',
    budget: 42000,
    status: 'Fieldwork',
    framework: 'IFRS',
    businessSize: 'Medium',
    isTaxReturnNeeded: false,
    createdAt: '2024-04-03T16:00:00Z',
    updatedAt: '2024-04-10T11:30:00Z'
  },
  {
    id: 'eng-003',
    proposalId: 'prop-004',
    requestId: 'req-003',
    clientName: 'Sunrise Retail',
    clientEmail: 'audit@sunriseretail.com',
    auditorName: 'David Thompson',
    auditorEmail: 'david.thompson@auditfirm.com',
    projectName: 'Sunrise Retail - Internal Controls Review',
    startDate: '2024-03-01',
    endDate: '2024-04-26',
    budget: 72000,
    status: 'Manager Review',
    framework: 'GAPSME',
    businessSize: 'Medium',
    isTaxReturnNeeded: true,
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-04-20T15:45:00Z'
  }
]; 